name: Build YuPomo (Windows, macOS, Linux)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: npm ci

      - name: Install Tauri CLI
        run: npm i -g @tauri-apps/cli

      - name: Generate platform icons (if missing)
        shell: bash
        run: |
          if [ ! -f src-tauri/icons/icon.icns ] && [ -f src-tauri/icons/android-chrome-512x512.png ]; then
            npx @tauri-apps/cli icon src-tauri/icons/android-chrome-512x512.png
          fi

      - name: Build app (Tauri)
        uses: tauri-apps/tauri-action@v0.5.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "YuPomo ${{ github.ref_name }}"
          releaseDraft: false
          prerelease: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: YuPomo-${{ runner.os }}
          path: |
            src-tauri/target/release/bundle/**
